# Generated by Django 3.2.4 on 2021-06-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('brand', models.CharField(max_length=240, verbose_name='Brand')),
                ('price', models.CharField(max_length=240, verbose_name='Price')),
                ('size', models.CharField(max_length=240, verbose_name='Size')),
                ('rms', models.CharField(max_length=240, verbose_name='RMS')),
                ('peak', models.CharField(max_length=240, verbose_name='Peak')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('registationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Title')),
                ('body', models.CharField(max_length=500, verbose_name='Body')),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.review'),
        ),
    ]
