# Generated by Django 3.2.4 on 2021-06-16 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_product_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('brand', models.CharField(max_length=240, verbose_name='Brand')),
                ('price', models.CharField(max_length=240, verbose_name='Price')),
                ('wattage', models.CharField(max_length=240, verbose_name='RMS')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.review')),
            ],
        ),
    ]
