# Generated by Django 3.2.4 on 2021-06-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_amp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amp',
            name='description',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='price',
        ),
        migrations.RemoveField(
            model_name='amp',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='amp',
            name='brand',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='amp',
            name='name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='amp',
            name='wattage',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='sub',
            name='brand',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='sub',
            name='peak',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='sub',
            name='rms',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=240),
        ),
        migrations.CreateModel(
            name='SubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('brand', models.CharField(max_length=240)),
                ('price', models.CharField(max_length=240)),
                ('size', models.CharField(max_length=240)),
                ('rms', models.CharField(max_length=240)),
                ('peak', models.CharField(max_length=240)),
                ('description', models.CharField(max_length=500)),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.review')),
            ],
        ),
        migrations.CreateModel(
            name='AmpPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('brand', models.CharField(max_length=240)),
                ('price', models.CharField(max_length=240)),
                ('wattage', models.CharField(max_length=240)),
                ('description', models.CharField(max_length=500)),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.review')),
            ],
        ),
    ]
